name: Angular CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: List directory contents  # This step will help you verify paths
        run: ls -R

      - name: Install dependencies
        run: npm install
        working-directory: ./Testdeployment  # Adjust path as needed

      - name: Build Angular project
        run: npm run build -- --prod
        working-directory: ./Testdeployment  # Adjust path as needed
