name: Angular CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print current directory
        run: pwd

      - name: List directory contents
        run: ls -R

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --force
        working-directory:   # Adjust path based on your actual repo structure

      - name: Build Angular project
        run: npm run build -- --prod
        working-directory:   # Adjust path based on your actual repo structure
